steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'clean', 'package' ]
    dir: '.'
    env:
        - 'GOOGLE_CLIENT_ID=426281130009-dn3galpcckg0hc69t6nkbhgpbg74a0f2.apps.googleusercontent.com'
        - 'GOOGLE_CLIENT_SECRET=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'
        - 'FACEBOOK_APP_ID=801997552024473'
        - 'FACEBOOK_CLIENT_SECRET=fbaea7e1e4426c3da6e9fdcd50736048'
        - 'GITHUB_CLIENT_ID=Ov23liUKNugKLHjpRZEF'
        - 'GITHUB_CLIENT_SECRET=be2fd885f1dfec969c3657a7a3754fbb3ebd2ea9'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'app', 'deploy' ]
    dir: '.'
    env:
        - 'GOOGLE_CLIENT_ID=426281130009-dn3galpcckg0hc69t6nkbhgpbg74a0f2.apps.googleusercontent.com'
        - 'GOOGLE_CLIENT_SECRET=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'
        - 'FACEBOOK_APP_ID=801997552024473'
        - 'FACEBOOK_CLIENT_SECRET=fbaea7e1e4426c3da6e9fdcd50736048'
        - 'GITHUB_CLIENT_ID=Ov23liUKNugKLHjpRZEF'
        - 'GITHUB_CLIENT_SECRET=be2fd885f1dfec969c3657a7a3754fbb3ebd2ea9'

timeout: 900s


options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
