steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'
    secretEnv:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - FACEBOOK_APP_ID
      - FACEBOOK_CLIENT_SECRET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: '.'
    secretEnv:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - FACEBOOK_APP_ID
      - FACEBOOK_CLIENT_SECRET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET

secrets:
  - secretEnv:
      GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID"
      GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET"
      FACEBOOK_APP_ID: "FACEBOOK_APP_ID"
      FACEBOOK_CLIENT_SECRET: "FACEBOOK_CLIENT_SECRET"
      GITHUB_CLIENT_ID: "GITHUB_CLIENT_ID"
      GITHUB_CLIENT_SECRET: "GITHUB_CLIENT_SECRET"
    secretManager:
      secret: "GOOGLE_CLIENT_ID"
      version: "latest"
